DROP TABLE IF EXIST multimedia_review;
DROP TABLE IF EXIST multimedia_content;
DROP TABLE IF EXIST multimedia_category;
DROP TABLE IF EXIST category;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS album_music;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS music;
DROP TABLE IF EXISTS multimedia;
